# Generated by Django 4.1.4 on 2024-08-17 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('total_price', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodcategory', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(default='null.jpeg', upload_to='files')),
                ('description', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('qnty', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('payment_status', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('order_id', models.CharField(default='', max_length=100)),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tb_cart')),
                ('menu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_menu')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('adrs', models.CharField(default='', max_length=100)),
                ('plc', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('utype', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('adrs', models.CharField(default='', max_length=100)),
                ('plc', models.CharField(default='', max_length=100)),
                ('licence_number', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(default='null.jpeg', upload_to='files')),
                ('status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('adrs', models.CharField(default='', max_length=100)),
                ('utype', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('restaurant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_worker_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_status', models.CharField(default='', max_length=100)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_order')),
                ('restaurant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_restaurant')),
                ('worker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_worker')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('card_name', models.CharField(default='', max_length=100)),
                ('card_number', models.CharField(default='', max_length=100)),
                ('card_date', models.CharField(default='', max_length=100)),
                ('card_cvv', models.CharField(default='', max_length=100)),
                ('pay_status', models.CharField(default='', max_length=100)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_order')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_register')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_order',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_register'),
        ),
        migrations.CreateModel(
            name='tbl_menu_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(blank=True, default=0, null=True)),
                ('msg', models.CharField(default='', max_length=100)),
                ('menu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_menu')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_register')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_menu',
            name='restaurant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_restaurant'),
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(blank=True, default=0, null=True)),
                ('msg', models.CharField(default='', max_length=100)),
                ('restaurant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_restaurant')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('total_guest', models.CharField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('items', models.TextField(blank=True, null=True)),
                ('booking_status', models.CharField(default='', max_length=100)),
                ('restaurant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_restaurant')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_register')),
            ],
        ),
        migrations.AddField(
            model_name='tb_cart',
            name='menu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_menu'),
        ),
        migrations.AddField(
            model_name='tb_cart',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prebookingapp.tbl_register'),
        ),
    ]
